### ISSUE TITLE
Can't replicate (run) the example

### ISSUE THREAD

**Issue by lmarzocchetti** [maksut/rayclj#1]
I'm trying to download the repository and run the basic window example. But after i load the library and set "--enable-preview" and "--enable-native-access=ALL-UNNAMED", raylib start but a window is not open and the REPL gave me this error:

java[14674:148066] *** Assertion failure in -[NSMenu _setMenuName:], NSMenu.m:777

<img width="1728" alt="Screenshot 2024-04-14 at 17 34 19" src="https://github.com/maksut/rayclj/assets/61746163/ce2bed25-ce3a-42a1-9819-5cdf2d26b186">

**Comment by maksut** [comment]
Sorry, I don't have a personal macbook so I can't test it on mac right now.

Just a guess; can you try it by disabling window decorations before `init-window` like:
```
  (rl/set-window-state :window-undecorated)
```

If you are willing to spend time on it then you can try a similar basic example with C to confirm the raylib 5.0 works in your set up before involving any java bindings.

**Comment by maksut** [comment]
Just to note, it looks like `InitWindow` fails (raylib initializes its stuff during that call). That assertion is likely coming from GLFW.

**Comment by lmarzocchetti** [comment]
Yeah the error is from glfw, its strange because i have glfw installed on my system and in my path

<img width="1728" alt="Screenshot 2024-04-14 at 18 33 41" src="https://github.com/maksut/rayclj/assets/61746163/ea18440f-344f-4fb3-8840-8e3c55e0f17f">
